spring:
  application:
    name: shopapp
  datasource:
    url : jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: nhan1811
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect
#      format_sql : true
  servlet:
   multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prelix: api/v1

server:
  port: 8088

jwt:
  experation: 2592000
  secretKey: nhan1811


